---
title: "Tech Meetups per City"
author: "Augustina Ragwitz"
date: "July 27, 2017"
output: html_document
params:
  meetup_api_key: !r Sys.getenv("API_KEY_MEETUP")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggmap)
library(httr)
library(jsonlite)
library(purrr)
library(tidyr)
```

## Cities of Interest
```{r geocode, include=FALSE, eval=FALSE}
cities <- c(
  "Austin",
  "Atlanta",
  "Boston",
  "Chicago",
  "Denver",
  "Detroit",
  "Durham",
  "Miami",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "San Francisco",
  "San Jose",
  "Seattle"
)

states <- c(
  "TX",
  "GA",
  "MA",
  "IL",
  "CO",
  "MI",
  "NC",
  "FL",
  "PA",
  "AZ",
  "OR",
  "CA",
  "CA",
  "WA"
)

locations <- data_frame(city=cities, state=states)
locations <- locations %>% mutate(
  city_state=paste(city, state)
)

locations <- bind_cols(locations, geocode(locations$city_state))

write.csv(locations, "meetup_geo.csv")
```

```{r}
meetup_geo <- read.csv("meetup_geo.csv")
```


```{r meetup_groups}

url <- "https://api.meetup.com/find/groups"

query_params <- list(
  key=params$meetup_api_key, 
  sign=TRUE,
  page=200,
  radius=50,
  category=34,
  order="most_active")

get_meetups <- function (url, query) {
  req <- GET(url, query=query)
  print(paste(req$url))
  json <- content(req, as = "text")
  groups <- fromJSON(json, flatten=TRUE)
  return(groups)
}

# # TODO figure out how to do this in purr; tried multiple things and failed
#meetup_groups_list <- mapply(get_groups, meetup_geo$lon, meetup_geo$lat)
# q <- mapply(append, query, meetup_geo$lon, meetup_geo$lat)

meetup_groups <- data_frame()

for (n in 1:nrow(meetup_geo)) {
  lon <- meetup_geo[n,]["lon"]
  lat <- meetup_geo[n,]["lat"]
  city <- meetup_geo[n,]["city_state"]
  print(paste("Getting groups for :", city$city))
  meetup_groups <- bind_rows(meetup_groups, 
                             get_meetups(url, append(query_params, c(lon=lon$lon, lat=lat$lat))))
  write.csv(meetup_groups, paste("meetup_groups/_meetup_groups_", n, ".csv", sep=""))
}

meetup_groups <- meetup_groups %>% 
  mutate(events_url = paste("https://api.meetup.com/", urlname, "/events", sep=""))

write.csv(meetup_groups, "meetup_groups.csv", row.names = FALSE, na = "")

```

```{r}
meetup_groups <- read.csv("meetup_groups.csv")

query_params <- list(
  key=params$meetup_api_key, 
  sign=TRUE,
  page=200,
  status="past",
  fields=paste("comment_count", "photo_album", sep=", ")
)

meetup_events <- data_frame()

```

```{r}
for (n in 1:nrow(meetup_groups)) {
  events_url <- meetup_groups[n,]["events_url"]
  print(paste("Trying url:", events_url$events_url))
  meetups <- get_meetups(events_url$events_url, query_params)
  if(length(meetups)== 0) {
    next()
  }

  meetups <- meetups %>% mutate(photo_album.photo_sample=NA)
  meetup_events <- bind_rows(meetup_events, meetups)
  write.csv(meetup_events, paste("meetup_events/_meetup_events_", n, ".csv", sep=""))
}


write.csv(meetup_events, "meetup_events.csv", row.names = FALSE, na = "")
```

```{r}
meetup_events <- read_csv("meetup_events.csv")
```


## Add MSA (Metropolitan Statistical Area) Designations to Meetups

Add cities that show up in Meetup searches but don't show up in the BLS list. It's not clear if these areas are part of the official BLS MSA but it's not unusual for people to live or work in these cities that also live and work in the main metropolitan region.

```{r}
metro_areas <- read.csv("../bls/qcew/qcew_msa.csv")
metro_areas_meetup_add <- read.csv("meetup_msa_add.csv")

metro_areas_meetup_add <- metro_areas_meetup_add %>% 
  inner_join(metro_areas, by="city_state", "msa_states") %>%
  rename(msa_cities=msa_cities.x, msa_states=msa_states.x) %>%
  select(-msa_cities.y, -msa_states.y) %>%
  unique()

metro_areas_meetups <- bind_rows(metro_areas, metro_areas_meetup_add)
write.csv(metro_areas_meetups, "metro_areas_meetups.csv", row.names = FALSE, na = "")
```


```{r}
meetup_groups <- read.csv("meetup_groups.csv")
metro_areas <- read.csv("metro_areas_meetups.csv")

meetups_metro <- meetup_groups %>% 
  left_join(metro_areas %>% select(area_fips, city_state, msa_cities, msa_states),
             by=c("city"="msa_cities", "state"="msa_states"))

meetups_metro_matched <- meetups_metro %>% 
  filter(!is.na(city_state)) %>%
  mutate(msa_states=state)

meetups_metro_na <- meetups_metro %>% 
  filter(is.na(city_state)) %>%
  inner_join(metro_areas %>% select(area_fips, city_state, msa_states, state),
             by=c("state")) %>%
  filter(as.character(state) == as.character(msa_states)) %>%
  select(-area_fips.x, -city_state.x) %>%
  rename(city_state=city_state.y, area_fips=area_fips.y) %>%
  unique()

# couldn't find a metro area for these, need to add it when we pull from meetup next time around
meetups_metro_missed <- meetups_metro %>% 
  anti_join(meetups_metro_na, by="id") %>%
  anti_join(meetups_metro_matched, by="id")
  

meetup_groups_msa <- bind_rows(meetups_metro_matched, meetups_metro_na, meetups_metro_missed)

write.csv(meetup_groups_msa, "meetup_groups_msa.csv", row.names = FALSE, na = "")
```

```{r}
meetup_groups_msa <- read.csv("meetup_groups_msa.csv", na="")
meetup_events <- read_csv("meetup_events.csv")

meetup_events_msa <- meetup_events %>% 
  inner_join(meetup_groups_msa %>% select(area_fips, city_state, msa_states, id),
             by=c("group.id"="id")) %>%
  unique()

meetup_events_msa_missing <- meetup_events %>% 
  anti_join(meetup_events_msa, by=c("id"))


```


